package com.demo.exceptions.demo3;

public class App2 {

	
	
	public int divide(int a,int b)
	{
		
		
		try
		{
			
			int c=a/b;
			System.out.println("no exception")
			
		}
		
		catch(ArithmeticException e)
		{
			
			System.out.println("hiii")
		}
	}
}
