package com.demo.exceptions;

public class ExceptionDemo2 {

	public static void main(String[] args) {
		try {
		
		int[] nums= {1,2,3,4};
		System.out.println(nums[4]);
		System.out.println("No exceptions found");
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println("Array Limit is being exceeded");
			
			
		}
		
	}
}