package com.demo.exceptions;

public class ExceptionDemo2 {

	public static void main(String[] args) {
		try {
		
		int[] nums= {1,2,3,4};
		System.out.println(nums[4]);
		System.out.println("No exceptions found");
		
		String[] names=new String[5];
		names[2].length();// string not populated. null of type string
		}
		catch(NullPointerException e)
		{
			e.printStackTrace();
			
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			//System.out.println("Array Limit is being exceeded");
			
			
		}
		
	}
}